### PR TITLE
Updates some traits, creates others and provides trait descriptors to use them in submissions

### LINKED ISSUE #661: Load/update new set of Trait data sent by Annemarie
Some of the traits are already present yet they need update. Accompanying Trait Descriptors should also be created.

### PR DESCRIPTION
**Pull request by Nuanda**
Fixes #661 

Ignoring created/updated Traits in rollback is intentional.

### CODE REVIEW

**Comment by Nuanda** [comment]
@kammerer Please take a look. This is needed for this Wed so it would be great if you could do it soon. I just mean - check if i haven't done something totally wrong.

**Comment by Nuanda** [comment]
Broken specs ar related to #659

**Comment by kammerer** [comment]
The only, minor, issue I see is formatting of scoring method, which is shown in the autocomplete field (the asterisks make it look a bit strange).

**Comment by kammerer** [comment]
:+1:

**Comment by Nuanda** [comment]
Yes, this is what I got. Rewriting it is a html list and interpreting user-provided content as html is rather a no go. Only "safe" things I could think of was to use js to replace client-side newlines with `br`s. Committed. Should I keep that change or leave things as they were?

**Comment by kammerer** [comment]
Keep it, IMHO looks a bit better.

**Pull request merged**
