### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by kammerer**
Update dependencies with known security vulnerabilities. I've more-or-less tested the application manually, all specs pass to.

### CODE REVIEW

**Comment by Nuanda** [comment]
Will capistrano fetch the new gem versions on deploy?

**Comment by kammerer** [comment]
Yes.

**Comment by Nuanda** [comment]
Updated gems locally and run all specs, so I guess this is :+1:

**Comment by Nuanda** [comment]
@kammerer I think I get a lot of DEPRECATION warnings after merging this in. Also Travis does. Do you know what is the reason of that?

**Comment by kammerer** [comment]
Probably updated RoR introduced those.

**Pull request merged**
