### PR TITLE
Privacy aware reindexing

### LINKED ISSUE #615: Deployment slow due to reindexing
Right now ES indices are reindexed on each deployment and that takes quite long time. However reindexing is not always necessary - it is needed only when we change the fields to be indexed. Two solutions come to my mind:

* enforce indexing on deployment with a special flag (skip it by default)
* enqueue indexing to be performed asynchronously after the deploy is completed 

@Nuanda WDYT?

### PR DESCRIPTION
**Pull request by kammerer**
Fixes #615 and #616 

After all, no special flag is needed for #615. Instead we will call `bin/cap production search:reindex:all` after performing deployment if rebuilding indices is needed.

### CODE REVIEW

**Comment by Nuanda** [comment]
Please update the README Deployment section (how one runs that task and when it is needed). Then: :+1:

**Comment by kammerer** [comment]
I wanted to fix issues with specs before merging this, but it appears that it will require digging deeper into ES. The problem is that specs randomly fail due to ES indices not being ready to be queried. I don't however know what is the underlying reason for that (sleeping does not help much).

**Comment by Nuanda** [comment]
No it doesn't, I tested that as well.

**Comment by kammerer** [comment]
Perhaps this is an issue with my instance of ES which has some unassigned shards and stays "red", however Travis shows similar behaviour.

**Comment by kammerer** [comment]
I fixed issues with my ES cluster and now specs pass consistently, so I think we can merge and fix travis later. Also, I enabled bundle caching on travis so that the build is a bit faster.

**Pull request merged**
