### PR TITLE
Licensing notice

### PR DESCRIPTION
**Pull request by teatree1212**
1) I added a new "documentation" page to join the header pages 
Home
Browse database
Submit data
Perform analysis
API documentation
About us

2) and changed the About us - section accordingly.

3) I also added  a few sentences about licensing of data to the submissions.en.yml

My local instance of BIP is currently not running, as I have an issue with the gems (I think I need libv8 but doing bundle install always runs into errors. What can I do?). So I could not check 100% whether what I did was right.

Could you have a look at what I have done?
I also don't know how to integrate the page from 1) actually into the interface so that it comes up as a link with all other headers.

### CODE REVIEW

**Comment by Nuanda** [comment]
@teatree1212 Where do you want to have the link to the new 'About BIP' page? Somewhere inside the current 'About us'? Directly on the BIP landing page?

**Comment by teatree1212** [comment]
on the landing page, as another page on the grey bar, besides ‘about us'

**Comment by Nuanda** [comment]
Should I rename the current one to "About EI" or "About us" or "About authors"?

**Comment by teatree1212** [comment]
keep it as About us for now.

**Comment by Nuanda** [comment]
It says "About" at the moment, but I get it.

**Comment by teatree1212** [comment]
sorry, then "About us"

**Comment by Nuanda** [comment]
The DataCite link is null. Should I simply use https://www.datacite.org/?

**Comment by teatree1212** [comment]
sorry, yes go for ti for now. I might change it afterwards.

**Comment by Nuanda** [comment]
There is no content inside the 'Embargo your data' section. Can you provide it? Should I maybe drop this section header?

**Comment by teatree1212** [comment]
drop this ( comment this out) for now, I need to hear back whether what I wrote sounds good. Wiktor was confused by my description. I am waiting to hear back from him.

**Comment by Nuanda** [comment]
Maybe we just leave this PR then for a second, then, and see when he comes back to us?

**Comment by Nuanda** [comment]
Deployed.

**Pull request merged**
