### PR TITLE
MIAPPE extensions for Trial submission

### LINKED ISSUE #758: New experimental variables in trial submission
Extend trial submission details to further experimental variables identified in the
process of discussing the new MIAPPE requirments such as described in the
following [table](https://docs.google.com/spreadsheets/d/1ICfgJOM11oqkql-g64XQqKeJSxOR5RwnkFZBRu6DsTk/edit#gid=989837895)

### PR DESCRIPTION
**Pull request by kammerer**
Fixes #758

This PR replaces #759 and covers both the new scalar fields as well as those which require additional dictionary and associative tables. It is quite a lot of code for one PR, sorry for that.

Overview of the changes:
1. Added new tables and models to store user provided data. This data inherits privacy status from the PT it belongs to. It is not yet shown anywhere, except to the owner.
2. Added new supplemental dictionary tables and models.
3. Added two new uploads to the PT submission form. Reordered steps so that the templates can be downloaded with minimal user effort.

### CODE REVIEW

**Comment by Nuanda** [comment]
Specs pass on my computer. However, I feel like reading and testing all that code again is a bit of a waste. Can you instead, perhaps, tell me what's new related to the old, deleted PR, and what should I focus my tests on?

**Comment by kammerer** [comment]
- In the old PR all numeric attributes were modelled as new columns in two database tables (`plant_trial_environments` and `plant_trial_treatments`). Now they are added as entirely new table `plant_trial_measurement_values`.
- More `PlantTrial::*TreatmentApplication` classes are added.
- New dictionary-based relations are added, e.g. `PlantTrial::Lamps`, `PlantTrial::Containers`.
- The most important thing from the UX point of view is the PT submission form and the new templates. It would probably be enough if you downloaded the templates and tried to upload some data. For dictionary-based attributes you should be to chose terms from drop-downs in the spreadsheet as well as enter entirely new terms. After finalization content should be visible in the submissions/show view (and only there, for now at least).

**Comment by Nuanda** [comment]
I had a problem with uploading Environment xls. This is what I get:

```
File contains invalid unit 'degree Celsius' for 'Average day temperature.'
File contains invalid unit 'degree Celsius' for 'Average night temperature.'
File contains invalid unit 'kelvin' for 'Change over the course of experiment.'
File contains invalid unit 'mol m−2s−1' for 'Average daily integrated photosynthetic photon flux density (PPFD) measured at plant level.'
```
Yes, I did change Celsius to kelvin in the third case, but (1) this was from the dropdown menu and (2) I didn't change the first two Celsius units. So apparently the parser is too prohibitive.

**Comment by kammerer** [comment]
I forgot to write that you need to run `rake db:seed` to populate dictionary tables, not sure if you did that. I use libreoffice too.

**Comment by Nuanda** [comment]
I've got the following error when finalizing:

```
ETHON: performed EASY effective_url=http://localhost:9200/brassica_development_plant_populations/plant_population/25 response_code=200 return_code=ok total_time=0.02024400000000004
   (0.3ms)  ROLLBACK
Completed 401 Unauthorized in 117ms (ActiveRecord: 15.0ms | Elasticsearch: 0.0ms)

ActiveRecord::RecordNotFound - Couldn't find PlantTreatmentType:
  activerecord (4.2.6) lib/active_record/core.rb:196:in `find_by!'
  app/services/submission/plant_trial_finalizer/treatment_builder.rb:37:in `find_or_build_treatment_type'
  app/services/submission/plant_trial_finalizer/treatment_builder.rb:31:in `block in build_treatment_application'
```
I am almost sure this is due to my elasticsearch problems (I'm not sure why, but the ES refuses to work for me locally recently), but please make sure this does not happen then the ES works ok.

**Comment by kammerer** [comment]
All right, thanks!

**Pull request merged**
