### PR TITLE
GWAS analysis with GAPIT package

### LINKED ISSUE #769: Running GWAS with GAPIT
Support for running GWAS with [GAPIT](http://www.maizegenetics.net/gapit). Provide set of forms and add possibility to set several parameters.

### PR DESCRIPTION
**Pull request by kammerer**
Fixes #769

Alternate method of running GWAS. GAPIT needs to be installed from [here](http://www.maizegenetics.net/gapit) (both `gapit_functions.txt` and `emma.txt`) and configured according to README.md.

Both types of GWAS support the same formats of input files, so it can be tested with e.g.:
* `spec/fixtures/files/gwas-phenotypes.csv` + `spec/fixtures/files/gwas-genotypes-transposed.csv`, or
* `spec/fixtures/files/gwas-phenotypes.csv` + `spec/fixtures/files/gwas-genotypes.vcf`, or
* `spec/fixtures/files/gwas-phenotypes.csv` + `spec/fixtures/files/gwas-genotypes.hapmap`, or
* [files from GAPIT tutorial](https://github.com/TGAC/brassica/files/1772666/gapit-tutorial.zip) (reformatted by me).

This is another big PR but many files are reused between GWASSER and GAPIT and are only moved/renamed. There are also many changes in existing specs and fixtures but these are not super important (mainly about handling special chars).

### CODE REVIEW

**Comment by kammerer** [comment]
I need to check spec failures on Travis but other than that it is ready for review.

**Comment by Nuanda** [comment]
I get this when running a job:

```
Data preprocessing failed. uninitialized constant Analysis::GenotypeHapmapMetadataAnalyzer
```
Adding the `Gwas` module name helps.

**Comment by Nuanda** [comment]
Output files, when downloaded, have strange "hash" names, instead of the ones listed on the analysis output page. Can that be helped?

**Comment by Nuanda** [comment]
Apart from the two remarks so far, this seems to work all right. I'll also try to see the code soon.

**Comment by kammerer** [comment]
I fixed the missing namespace issue and made downloads show correct file name. Also, I fixed specs related to this PR.

**Comment by Nuanda** [comment]
One more test is not deterministic:

 ```
 4) Analysis::Gwas::PlantTrialPhenotypeCsvBuilder#build_csv returns CSV acceptable by GWASSER
     Failure/Error: expect(headers).to eq(['"ID"'] + trait_names.map { |t| %("#{t}") })
     
       expected: ["\"ID\"", "\"enim_361\"", "\"est_362\"", "\"est_363\""]
            got: ["\"ID\"", "\"enim_361\"", "\"est_363\"", "\"est_362\""]
     
       (compared using ==)
 ```

**Pull request merged**
